version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
  api:
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
